update CHS translation
team-abnormals/autumnity pull request #43
Opened 2021-01-02 04:32 UTC by TUsama

2021-01-02 04:32 UTC, TUsama commented
@WuzgXY-GitHub

2021-01-03 01:26 UTC, WuzgXY-GitHub requested changes

2021-01-03 01:26 UTC, WuzgXY-GitHub commented on src/main/resources/assets/autumnity/lang/zh_cn.json
>    "block.autumnity.stripped_maple_log": "去皮枫木原木",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

统一改为「枫树」（包括其它所有「枫木」）会更好（我在看 L44 和 L45）

2021-01-03 01:26 UTC, WuzgXY-GitHub commented on src/main/resources/assets/autumnity/lang/zh_cn.json
> +  "subtitles.entity.turkey.egg": "火鸡：下蛋的噗噗声",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

```suggestion
  "subtitles.entity.turkey.egg": "火鸡：噗噗下蛋",
```

按照规范，不应出现动作声词化的现象

2021-01-03 01:26 UTC, WuzgXY-GitHub commented on src/main/resources/assets/autumnity/lang/zh_cn.json
> +  "block.minecraft.banner.mca_swirl.light蓝色": "浅蓝色螺旋",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

不怪你，这确实麻烦

2021-01-03 01:26 UTC, WuzgXY-GitHub commented on src/main/resources/assets/autumnity/lang/zh_cn.json
> +  "block.minecraft.banner.mca_maple_leaf.light蓝色": "浅蓝色枫叶",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

这个我自己改了，刚发现我有编辑文件的权限

2021-01-03 01:26 UTC, WuzgXY-GitHub commented on src/main/resources/assets/autumnity/lang/zh_cn.json
> +  "block.autumnity.slime": "史莱姆",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

请进入游戏确认

2021-01-03 01:28 UTC, WuzgXY-GitHub commented on src/main/resources/assets/autumnity/lang/zh_cn.json
> +  "block.minecraft.banner.mca_swirl.light蓝色": "浅蓝色螺旋",
已解决

2021-01-03 01:28 UTC, WuzgXY-GitHub commented on src/main/resources/assets/autumnity/lang/zh_cn.json
> +  "block.minecraft.banner.mca_maple_leaf.light蓝色": "浅蓝色枫叶",
已解决

2021-01-03 02:19 UTC, WuzgXY-GitHub approved these changes

2021-01-05 02:52 UTC, merged